import { ArrowRight, MousePointerClick, Route, Send, Smartphone, WalletCards } from 'lucide-react';
import { PageHeader, ProgressBar } from '@/components/ui';
import { getDashboardSourceBreakdown } from '@/lib/data';

export default async function AttributionPage() {
  const sourceBreakdown = await getDashboardSourceBreakdown();
  return <>
    <PageHeader eyebrow="Customer journey" title="Attribution" description="Keep first marketing touch, lead-creation channel, current contact channel and conversion touch separate so each channel gets the right credit." />
    <div className="grid gap-4 lg:grid-cols-4"><Step icon={<MousePointerClick size={18}/>} title="First touch" value="Acquisition" note="Paid, organic or referral" /><Step icon={<Send size={18}/>} title="Lead created" value="Enquiry channel" note="Website, DM, form or WhatsApp" /><Step icon={<Smartphone size={18}/>} title="Current channel" value="Conversation" note="Where admissions is talking now" /><Step icon={<WalletCards size={18}/>} title="Conversion touch" value="Deposit / enrollment" note="Closing event and channel" /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.8fr_1.2fr]">
      <div className="card-pad"><div className="eyebrow">First-touch mix</div><div className="section-title mt-1">Where discovery starts</div><div className="mt-5 space-y-5">{sourceBreakdown.length ? sourceBreakdown.map(s=><div key={s.source}><div className="mb-2 flex justify-between"><span className="text-sm font-semibold text-slate-700">{s.source}</span><span className="text-sm font-bold">{s.share}%</span></div><ProgressBar value={s.share}/><div className="mt-1 text-[11px] text-slate-400">{s.leads} leads · {s.qualified} qualified+</div></div>) : <div className="text-sm text-slate-500">No attributed leads yet.</div>}</div></div>
      <div className="card-pad"><div className="eyebrow">Journey model</div><div className="section-title mt-1">One lead, multiple channels</div><div className="mt-8 flex flex-col gap-3 xl:flex-row xl:items-center">{[['Google Ad','First acquisition'],['Website','Course + accommodation'],['Instagram','DM enquiry'],['WhatsApp','Booking discussion'],['Deposit','Conversion']].map(([a,b],i)=><div key={a} className="contents"><div className="flex-1 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="text-sm font-bold text-slate-900">{a}</div><div className="mt-1 text-xs leading-5 text-slate-500">{b}</div></div>{i<4&&<ArrowRight className="mx-auto shrink-0 rotate-90 text-slate-300 xl:rotate-0" size={18}/>}</div>)}</div><div className="mt-6 rounded-2xl border border-brand/10 bg-brand/[.04] p-4"><div className="flex items-center gap-2 text-sm font-bold text-brand"><Route size={16}/> Attribution rule</div><p className="mt-2 text-sm leading-6 text-slate-600">Later direct visits and the channel that closes the enrollment do not overwrite the original marketing acquisition. v0.6 stores anonymous website touchpoints first, links them to the lead after identification, and keeps future website events attached to that lead.</p></div></div>
    </div>
  </>;
}
function Step({icon,title,value,note}:{icon:React.ReactNode;title:string;value:string;note:string}){return <div className="card-pad"><div className="grid h-10 w-10 place-items-center rounded-xl bg-brand/10 text-brand">{icon}</div><div className="mt-4 text-xs font-semibold text-slate-400">{title}</div><div className="mt-1 text-lg font-bold text-slate-900">{value}</div><div className="mt-1 text-xs text-slate-500">{note}</div></div>}
