import { PageHeader } from '@/components/ui';
import { getCampaigns } from '@/lib/data';
import { formatCompactINR } from '@/lib/format';

export default async function CampaignsPage() {
  const campaigns = await getCampaigns();
  const totals = campaigns.reduce((a,c) => ({ spend: a.spend+c.spend, leads: a.leads+c.leads, qualified: a.qualified+c.qualified, enrolled: a.enrolled+c.enrolled, revenue: a.revenue+c.revenue }), {spend:0,leads:0,qualified:0,enrolled:0,revenue:0});
  return <><PageHeader eyebrow="Paid acquisition" title="Campaigns" description="Campaign reporting tied to CRM outcomes, so you can compare lead volume with qualified leads, enrollments and revenue." actions={<button className="btn-secondary">September 2026</button>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Spend" value={formatCompactINR(totals.spend)} /><Metric label="Leads" value={totals.leads.toLocaleString('en-IN')} /><Metric label="Qualified" value={totals.qualified.toLocaleString('en-IN')} /><Metric label="Enrolled" value={totals.enrolled.toLocaleString('en-IN')} /><Metric label="Revenue" value={formatCompactINR(totals.revenue)} /></div><div className="mt-4 card overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-left"><thead><tr className="border-b border-slate-200 bg-slate-50 text-[11px] uppercase tracking-[.1em] text-slate-400">{['Campaign','Platform','Spend','Leads','Qualified','Enrolled','CPL','CPQL','CAC','ROAS'].map(h=><th key={h} className="px-4 py-3 font-bold">{h}</th>)}</tr></thead><tbody>{campaigns.map(c => { const cpl=c.spend/c.leads, cpql=c.spend/c.qualified, cac=c.spend/c.enrolled, roas=c.revenue/c.spend; return <tr key={c.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50"><td className="px-4 py-4"><div className="font-semibold text-slate-900">{c.name}</div></td><td className="px-4 py-4 text-sm text-slate-600">{c.platform}</td><td className="px-4 py-4 text-sm font-semibold">{formatCompactINR(c.spend)}</td><td className="px-4 py-4 text-sm">{c.leads}</td><td className="px-4 py-4 text-sm">{c.qualified}</td><td className="px-4 py-4 text-sm">{c.enrolled}</td><td className="px-4 py-4 text-sm">₹{Math.round(cpl)}</td><td className="px-4 py-4 text-sm">₹{Math.round(cpql).toLocaleString('en-IN')}</td><td className="px-4 py-4 text-sm">₹{Math.round(cac).toLocaleString('en-IN')}</td><td className="px-4 py-4 text-sm font-bold text-emerald-600">{roas.toFixed(1)}×</td></tr>})}</tbody></table></div></div></>;
}
function Metric({ label, value }: { label:string; value:string }) { return <div className="card-pad"><div className="text-sm text-slate-500">{label}</div><div className="mt-2 text-2xl font-bold text-slate-950">{value}</div></div>; }
